version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-docker-node-lambda-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_image_repos = true
