AWSTemplateFormatVersion: '2010-09-09'
  
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageName:
    Description: "Tag of the docker image used"
    Type: String
    Default: my-node-lambda
  ImageTag:
    Description: "Tag of the docker image used"
    Type: String
    Default: latest
  ImageArchitecture:
    Description: "Architecture of the docker image: arm64 or x86_64"
    Type: String
    Default: arm64

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}:${ImageTag}"
      MemorySize: 128
      Timeout: 30
      Architectures: 
        - !Ref ImageArchitecture
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        PostResource:
          Type: Api
          Properties:
            Path: /hello
            Method: post

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
    Description: URL for the API endpoint
